log:
  level: debug
http:
  port: 8080
neo4j:
  uri: bolt://localhost:7687
  username: neo4j
  password: password
openrouter:
  baseurl: https://openrouter.ai/api/v1
embedding:
  model: text-embedding-3-small
  dimensions: 1536
